CREATE TABLE EMPLOYEE
(
  ID UUID NOT NULL,
  TITLE CHARACTER VARYING(255),
  NAME CHARACTER VARYING(255) NOT NULL,
  SURNAME CHARACTER VARYING(255) NOT NULL,
  EMPLOYEE_TITLE CHARACTER VARYING(255) NOT NULL,
  BIO CHARACTER VARYING(255) NOT NULL,
  IMAGE_NAME CHARACTER VARYING(255) NOT NULL,
  EXTENSION JSONB,
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT,
  CATEGORY_ID BIGINT,
  CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY (ID),
  CONSTRAINT FKBEJTWVG9BXUS2MFFSM3SWJ3U9 FOREIGN KEY (DEPARTMENT_ID)
      REFERENCES DEPARTMENT (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
      CONSTRAINT FKBP91O1GYK9XQ5T48ZVGLAJ0ML FOREIGN KEY (CATEGORY_ID)
      REFERENCES CATEGORY (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FKGA73HDTPB67TWLR9C1I337TYT FOREIGN KEY (ADDRESS_ID)
      REFERENCES ADDRESS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);